### ISSUE TITLE
report.php mixes inline php and functions

### ISSUE THREAD

**Issue by danmarsden** [Palumdo/moodle-mod_dynamo#3]
functions should be moved into a lib file like locallib.php and need to follow our frankenstyle naming conventions:
https://docs.moodle.org/dev/Frankenstyle#Function_names

**Comment by danmarsden** [comment]
another hidden function in a file that doesn't follow our naming guidelines (and should not be in the in-line php file)
https://github.com/Palumdo/moodle-mod_dynamo/blob/master/teacherlvl1.php#L442

**Comment by Palumdo** [comment]
Hi Dan,

the function was put in the lovcal lib and prefixed with dynamo_

Thank you,

Dominique.
