### ISSUE TITLE
Never trust input from users.

### ISSUE THREAD

**Issue by danmarsden** [Palumdo/moodle-mod_dynamo#4]
direct access to raw $_GET/$_POST/$_REQUEST is not allowed.

https://github.com/Palumdo/moodle-mod_dynamo/blob/master/save.php#L79-L100 etc

Please change this to using moodle's optional/required_param functions with appropriate PARAM_XXX cleaning.

note - this is a blocker for approval in the plugins db. 

more info here:
https://docs.moodle.org/dev/Security#Don.27t_trust_any_input_from_users

**Comment by Palumdo** [comment]
Hi Dan,

I've use required_param, optional_param for all $_post. $_post is not used anymore.
I also add a check on session key confirm_sesskey() && data_submitted.
I've also use format_string() before the comments was saved.

Thank you,

Dominique.
