### ISSUE TITLE
trim() used with boolean as argument

### ISSUE THREAD

**Issue by tmuras** [Palumdo/moodle-mod_dynamo#7]
In:
https://github.com/Palumdo/moodle-mod_dynamo/blob/e8af2ad26ad7b4887775e636bd29d3885eb11c41/save.php#L107

trim function has boolean as the argument $comment1 == ''.

What you probably meant is to run trim on $comment1:
            if (trim($comment1) == '') {

The same for $comment2 below.

**Comment by Palumdo** [comment]
Hi,

Thank you. I'm confused to let a bug like that... 

Dominique.
