### ISSUE TITLE
Notices in mod/dynamo/view.php?id=18&groupid=0&usrid=0&tab=1

### ISSUE THREAD

**Issue by tmuras** [Palumdo/moodle-mod_dynamo#8]
When adding a new module in empty Moodle 4.0 I get the notices:

( ! ) Notice: Trying to get property 'id' of non-object in /var/www/html/moodle40/mod/dynamo/lib.php on line 1084
Call Stack
#	Time	Memory	Function	Location
1	0.0000	363816	{main}( )	.../view.php:0
2	0.1675	8222456	require_once( '/var/www/html/moodle40/mod/dynamo/student.php' )	.../view.php:169
3	0.1679	8222968	dynamo_get_body_table_teacher( )	.../student.php:148

( ! ) Notice: Trying to get property 'id' of non-object in /var/www/html/moodle40/mod/dynamo/lib.php on line 1098
Call Stack
#	Time	Memory	Function	Location
1	0.0000	363816	{main}( )	.../view.php:0
2	0.1675	8222456	require_once( '/var/www/html/moodle40/mod/dynamo/student.php' )	.../view.php:169
3	0.1679	8222968	dynamo_get_body_table_teacher( )	.../student.php:148

![image](https://user-images.githubusercontent.com/695281/179371809-93932bcd-f732-40ef-bcc5-1c6780146285.png)

**Comment by Palumdo** [comment]
Hi,

Thank you again. 
I've test all the functionality with no data at all and not enough data and add testing to avoid mostly division by zero error.

Dominique.
