### ISSUE TITLE
Hardcoded?

### ISSUE THREAD

**Issue by dinism** [Palumdo/moodle-mod_dynamo#9]
Thanks for the plugin.
I'm a PT-PT translator.

Is this hardcoded to French?
![imagem](https://user-images.githubusercontent.com/14828021/187471758-52c8f070-ae98-40de-8555-b82cbf182167.png)

**Comment by Palumdo** [comment]
Hi dinism,

it's in fact harcoded. I'll update today the correction in the git.  (line 529 in lib.php => <td style="min-width:200px;font-weight:bold;">'.get_string('dynamogroup', 'mod_dynamo').'</td>
